### ISSUE TITLE
Start script works in Unix environments, but not in Windows.

### ISSUE THREAD

**Issue by TheCornelius** [openpromisesmy/ui#232]
ERROR MESSAGE:
`NODE_ENV is not a recognizable internal or external command, or batch file`

(TEMPORARY) SOLUTION ON WINDOWS:
`SET NODE_ENV=development`

**Comment by nazreen** [comment]
this issue will be made non-existent if we implement containerization using Docker for local development

**Comment by TheCornelius** [comment]
Dockerized by Nazreen.
