### ISSUE TITLE
about page: logo is TOO BIG

### ISSUE THREAD

**Issue by nazreen** [openpromisesmy/ui#237]
the page is at `/about`
the component to be updated is at: `src/views/About.vue`
you only need to change the `<style>` section of the file
the image size should have a max-width so it stays in proportion
suggested max-width: around 300px

Cornelius has found the solution, apply the following css rule to the img element for the logo:
```
max-width: 270px;
width: auto;
margin-bottom: 20px;
```

**Comment by nazreen** [comment]
![image](https://user-images.githubusercontent.com/10964594/78562159-d8c7bd00-7810-11ea-9839-64ab71f18ec7.png)

**Comment by TheCornelius** [comment]
Closed by #242
