### ISSUE TITLE
views/Politician: when no promises, display spec

### ISSUE THREAD

**Issue by nazreen** [openpromisesmy/ui#240]
currently, for a politician page such as `/politician/7TcN9D2JhoYUH1bfS8er `
if the politician has no promises, the table will display: `Sorry, no promise matches your search.`
it should instead say: `There have been no promises uploaded yet for this politician. Did we miss a promise? Submit a promise now to help us fill that gap.`

'Submit a promise' should link to `/submit`

**Comment by TheCornelius** [comment]
Closed by #242
