### ISSUE TITLE
Error when installing dependencies

### ISSUE THREAD

**Issue by TheCornelius** [openpromisesmy/ui#241]
**Ran into errors after an attempt on running 'npm ci' and 'npm install'.**
Node version: 12.16.1
NPM version: 6.13.4
OS: Windows 10 Home

**After running 'npm ci'**

> npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with 'npm install' before continuing.
npm ERR!
npm ERR!
npm ERR! Invalid: lock file's axios@0.19.0 does not satisfy axios@^0.18.0
npm ERR! Missing: vue-typer@^1.2.0
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2020-04-17T01_20_56_902Z-debug.log

**After running 'npm install'**

> \> grpc@1.16.1 install C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc
> \> node-pre-gyp install --fallback-to-build --library=static_library
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.16.1/node-v72-win32-x64-unknown.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for grpc@1.16.1 and node@12.16.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
> gyp ERR! find VS
> gyp ERR! find VS msvs_version not set from command line or npm config
> gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
> gyp ERR! find VS looking for Visual Studio 2015
> gyp ERR! find VS - not found
> gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> gyp ERR! find VS
> gyp ERR! find VS **************************************************************
> gyp ERR! find VS You need to install the latest version of Visual Studio
> gyp ERR! find VS including the "Desktop development with C++" workload.
> gyp ERR! find VS For more information consult the documentation at:
> gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> gyp ERR! find VS **************************************************************
> gyp ERR! find VS
> gyp ERR! configure error
> gyp ERR! stack Error: Could not find any Visual Studio installation to use
> gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
> gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
> gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
> gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Username\\Desktop\\OpenPromises\\ui-2\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Username\\Desktop\\OpenPromises\\ui-2\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> gyp ERR! cwd C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc
> gyp ERR! node -v v12.16.1
> gyp ERR! node-gyp -v v5.0.5
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> node-pre-gyp ERR! System Windows_NT 10.0.18363
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Username\\Desktop\\OpenPromises\\ui-2\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
> node-pre-gyp ERR! cwd C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc
> node-pre-gyp ERR! node -v v12.16.1
> node-pre-gyp ERR! node-pre-gyp -v v0.12.0
> node-pre-gyp ERR! not ok
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\webpack-dev-server\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! grpc@1.16.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the grpc@1.16.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2020-04-17T01_25_52_373Z-debug.log

Based on the following line, it seems like grpc@1.16.1 is not compatible with Node 12.
`
Failed at the grpc@1.16.1 install script.
`

**After running 'npm run dev'**
> This dependency was not found:
> * firebase in ./src/config/index.js
> To install it, you can run: npm install --save firebase

After installing firebase, axios and vue-typer, re-running the development server gives the following errors, and _localhost:8080_ shows a blank HTML page with this line of text "Cannot GET /".

> > op-ui-2@1.0.0 dev C:\Users\corne\Desktop\OpenPromises\ui-2
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

> 
>  94% asset optimization
> 
>  ERROR  Failed to compile with 1 errors                                                                       9:34:47 AM
>  error  in ./node_modules/vue-goodshare/src/providers/Facebook.vue?vue&type=style&index=0&id=71552819&scoped=true&lang=scss&
> 
> Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v4.11.0
>     at module.exports (C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\node-sass\lib\binding.js:13:13)
>     at Object.<anonymous> (C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\node-sass\lib\index.js:14:35)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Module.load (internal/modules/cjs/loader.js:1002:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>     at Module.require (internal/modules/cjs/loader.js:1044:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.sassLoader (C:\Users\Username\Desktop\OpenPromises\ui-2\node_modules\sass-loader\lib\loader.js:46:72)
> 
>  @ ./node_modules/vue-style-loader!./node_modules/css-loader??ref--10-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--10-2!./node_modules/sass-loader/lib/loader.js??ref--10-3!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-goodshare/src/providers/Facebook.vue?vue&type=style&index=0&id=71552819&scoped=true&lang=scss& 4:14-337 14:3-18:5 15:22-345
>  @ ./node_modules/vue-goodshare/src/providers/Facebook.vue?vue&type=style&index=0&id=71552819&scoped=true&lang=scss&
>  @ ./node_modules/vue-goodshare/src/providers/Facebook.vue
>  @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Politician/Desktop.vue?vue&type=script&lang=js&
>  @ ./src/components/Politician/Desktop.vue?vue&type=script&lang=js&
>  @ ./src/components/Politician/Desktop.vue
>  @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Politician.vue?vue&type=script&lang=js&
>  @ ./src/views/Politician.vue?vue&type=script&lang=js&
>  @ ./src/views/Politician.vue
>  @ ./src/router/index.js
>  @ ./src/main.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by nazreen** [comment]
@TheCornelius on this same machine do you have Docker installed already?

**Comment by nazreen** [comment]
in the meantime, please try changing your node version to 10, then retry `npm i` then `npm start`
you can use https://github.com/nvm-sh/nvm

**Comment by nazreen** [comment]
fyi for any npm project, pay attention to the `engines` attribute in `package.json` (if set): https://github.com/OpenPromisesProject/ui-2/blob/master/package.json

for this project it states 10 or above, but evidently there are issues for 12 so we should stick to 10. still, looking at the engines attribute will give you a clue as to which node version is probably going to work.

**Comment by TheCornelius** [comment]
> @TheCornelius on this same machine do you have Docker installed already?

Not running on Docker, can't install it on this same machine as Docker Desktop requires Windows 10 Pro.

> fyi for any npm project, pay attention to the `engines` attribute in `package.json` (if set): https://github.com/OpenPromisesProject/ui-2/blob/master/package.json
> 
> for this project it states 10 or above, but evidently there are issues for 12 so we should stick to 10. still, looking at the engines attribute will give you a clue as to which node version is probably going to work.

All right, noted with thanks.

**Comment by nazreen** [comment]
"Windows 10 Home edition does not support Hyper-V see here: https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/quick_start/walkthrough_compatibility 10.9k

This does not mean you can’t use Docker you just can’t use the Hyper-V version of it but you can use the VirtualBox version."

**Comment by nazreen** [comment]
solution: use node 10 as specified in package.json
