### ISSUE TITLE
Unsuitable copy for politician promises filtered query

### ISSUE THREAD

**Issue by TheCornelius** [openpromisesmy/ui#243]
At every politician's page, when the user searches for a promise that does not exists, the following text is shown. 

`There have been no promises uploaded yet for this politician. Did we miss a promise? Submit a promise now to help us fill that gap`

From the user's perspective, it would be more suitable to show a response similar to this:
`There are no promises related to {query} for {politician}.`

Component involved: PromisesTable.vue

**Comment by nazreen** [comment]
the solution to this depends on conditional logics based on 2 properties in the `PromisesTable` component: `promises` (prop) and `filteredPromises` (computed)

suppose the 2 error messages are named (only for clarity sake) so:

`NO_PROMISES_UPLOADED`: "There have been no promises uploaded yet for this politician. Did we miss a promise? Submit a promise now to help us fill that gap"

`NO_MATCH`: "There are no promises related to {query} for {politician}."

then, that means, these are the conditions with the appropriate error messages

`promises.length === 0` => `NO_PROMISES_UPLOADED`

`promises.length > 0 && filteredPromises.length === 0` => `NO_MATCH`

the solution should utilise vue's `v-if` directives and only affect the `<template>` section
