### ISSUE TITLE
feat: create desktop and mobile design for displaying the Cabinet

### ISSUE THREAD

**Issue by nazreen** [openpromisesmy/ui#256]
**Is your feature request related to a problem? Please describe.**
moving forward, we want to highlight ministerial positions rather than individuals. we will not be doing states.

**Describe the solution you'd like**
A simple UI that displays all the politicians in the cabinet, emphasising the cabinet structure. This means the UI will most likely separate politicians based on ministries.

**Additional context**
The mockup does not need to list all ministries, perhaps just 6 to start off with. The. mockup needs to be done for both desktop and mobile.
This is an additive feature. It will not change or remove from existing features.

**Comment by nazreen** [comment]
@TheCornelius after you export the mockups you've done, we can close this issue. You can send the mockups via Slack.

**Comment by TheCornelius** [comment]
**Cabinet Based Design**
Mobile Browser View: https://xd.adobe.com/view/d08c2436-b660-48e9-5196-34b97548bb6e-a6bd/
Desktop Browser View: https://xd.adobe.com/view/70f0becb-2f71-4939-5473-ad742aa77cc5-06c1/
