### ISSUE TITLE
refactor(): cleanup Promises handlers

### ISSUE THREAD

**Issue by nazreen** [openpromisesmy/ui#76]

**Comment by nazreen** [comment]
@umarrasydan the root of this is actually the whole situation where some live Promises are by politicians that are not live.

we have several routes to go about this.

either way the ability to take a politician offline (live = false) should be retained

the paths to take:
1) on API side, ensure that the /promises/ endpoint returns only live promises by live politicians
- this might be very expensive as it needs to check each politician's live value based on politician_id of the promise
2) create a handler whereby when a politician is taken offline, all their promises will be updated as offline too 
- we'd need both setPromisesToLive and setPromisesOffline methods

Aside from the above I feel like we should utilise the 'Status' field of politicians. The values can be 'active' and 'inactive'
We can have a separate section for inactive politicians

**Comment by nazreen** [comment]
in short, this task is also blocked by the mentioned API design problem

**Comment by umarrasydan** [comment]
We should definitely go with number 2
