### ISSUE TITLE
Navbar bug

### ISSUE THREAD

**Issue by umarrasydan** [openpromisesmy/ui#79]
navbar only work by clicking the text. clicking the box only changes the look of the box which makes the site feels non responsive

**Comment by shiburagi** [comment]
already fixed for mobile version.

**Comment by nazreen** [comment]
@umarrasydan  can you layout steps needed to resolve this?

**Comment by shiburagi** [comment]
The issue with the ```<a>``` element's height & width didn't match with  parent element.
