### ISSUE TITLE
feat(Promise): setup Facebook comments

### ISSUE THREAD

**Issue by nazreen** [openpromisesmy/ui#81]
- [x] research how
- [x] implement

**Comment by alandotic** [comment]
meaning to comment on openpromise web with facebook profile details?

**Comment by nazreen** [comment]
@alandotic so for example on [this page](https://www.openpromises.com/promises/-LAczErcvfvhddL4uTH2 )
we want to setup this: https://developers.facebook.com/docs/plugins/comments/

**Comment by alandotic** [comment]
I'll do this

**Comment by alandotic** [comment]
I've completed locally, what's next? any branch for me?

**Comment by openpromises** [comment]
Upload branch and open pull request :)
