### ISSUE TITLE
router-link doesn't refresh the content, intended?

### ISSUE THREAD

**Issue by alandotic** [openpromisesmy/ui#97]
Hi, while i am working on FacebookComment, i found this behavior using Fiddler :
![image](https://user-images.githubusercontent.com/17924670/43175125-33a6282a-8ff0-11e8-8c6c-78e3945137a2.png)

the diagram consists of 2 requests, seperated by example.com request. one is navigated from http://localhost:8080/promises and another is refresh on http://localhost:8080/promises/-LAczEmpoAsZp9HOPjYx , noted that the fb sdk is not loaded on the first request(router-link) but it was loaded on the second request (F5).

Is this feature from vue or bug?

**Comment by openpromises** [comment]
Definitely a bug. I experienced something similar before on a react
project. The cause was that it was trying to inject into the div with the
fb id before it was in sight. Might be a similar cause. I did create this
issue yesterday #90
